时间:2014-05-14 18:13:10,967 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1150] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:13:40,800 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1150] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:14:10,806 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1128] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:14:40,823 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1159] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:15:10,852 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1128] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:15:40,884 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1131] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:16:10,898 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1166] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:16:40,916 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1128] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
时间:2014-05-14 18:17:10,929 
级别:ERROR 
类名:Wings.Logger
文件:g:\GitHub\Wings\Wings\Wings.Framework\Log\Log.cs 第95行
 [1153] 
 日志内容:【心跳】异常

-----------------------------------------

System.ServiceModel.CommunicationObjectFaultedException: 通信对象 System.ServiceModel.Channels.ServiceChannel 无法用于通信，因为其处于“出错”状态。

Server stack trace: 
   在 System.ServiceModel.Channels.CommunicationObject.ThrowIfDisposedOrNotOpen()
   在 System.ServiceModel.Channels.ServiceChannel.Call(String action, Boolean oneway, ProxyOperationRuntime operation, Object[] ins, Object[] outs, TimeSpan timeout)
   在 System.ServiceModel.Channels.ServiceChannelProxy.InvokeService(IMethodCallMessage methodCall, ProxyOperationRuntime operation)
   在 System.ServiceModel.Channels.ServiceChannelProxy.Invoke(IMessage message)

Exception rethrown at [0]: 
   在 System.Runtime.Remoting.Proxies.RealProxy.HandleReturnMessage(IMessage reqMsg, IMessage retMsg)
   在 System.Runtime.Remoting.Proxies.RealProxy.PrivateInvoke(MessageData& msgData, Int32 type)
   在 Wings.Framework.Plugin.Contracts.IPluginService.OnlineHeartbeat(Guid accountid, Guid webid)
   在 Wings.Framework.Plugin.PluginsManger.<.cctor>b__0(Object t) 位置 g:\GitHub\Wings\Wings\Wings.Framework\Plugin\PluginsManger.cs:行号 24
